"""Initial schema

Revision ID: 34f42fe6499f
Revises: 
Create Date: 2026-08-06 21:40:01.554009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f42fe6499f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.schema.CreateSequence(sa.Sequence('client_payment_order_number_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifetime_slots', sa.Integer(), nullable=False),
    sa.Column('agreed_to_tos_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_auto_renew', sa.Boolean(), nullable=False),
    sa.Column('subscription_payment_method_enc', sa.LargeBinary(), nullable=True),
    sa.Column('subscription_retry_count', sa.Integer(), nullable=False),
    sa.Column('subscription_next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_receipts_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_billing_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('bot_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('tg_bot_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.Column('is_token_locked', sa.Boolean(), nullable=False),
    sa.Column('has_lifetime_license', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('offer_url', sa.Text(), nullable=True),
    sa.Column('offer_installments', sa.Boolean(), nullable=False),
    sa.Column('funnel_complete', sa.Boolean(), nullable=False),
    sa.Column('media_sync_done', sa.Boolean(), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('payment_creds_enc', sa.LargeBinary(), nullable=True),
    sa.Column('funnel_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_tg_bot_id'), 'bots', ['tg_bot_id'], unique=True)
    op.create_table('saas_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotence_key', sa.String(length=64), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saas_payments_idempotence_key'), 'saas_payments', ['idempotence_key'], unique=True)
    op.create_index(op.f('ix_saas_payments_yookassa_payment_id'), 'saas_payments', ['yookassa_payment_id'], unique=True)
    op.create_table('connected_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chat_type', sa.String(length=32), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'chat_id', name='uq_connected_chats_bot_chat')
    )
    op.create_index(op.f('ix_connected_chats_bot_id'), 'connected_chats', ['bot_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('current_step_id', sa.String(length=255), nullable=False),
    sa.Column('agreed_to_tos', sa.Boolean(), nullable=False),
    sa.Column('has_purchased', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_has_purchased'), 'leads', ['has_purchased'], unique=False)
    op.create_index(op.f('ix_leads_telegram_id'), 'leads', ['telegram_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_bot_id'), 'media_assets', ['bot_id'], unique=False)
    op.create_table('client_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_order_number', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('invoice_batch_id', sa.UUID(), nullable=True),
    sa.Column('tariff_id', sa.String(length=128), nullable=False),
    sa.Column('tariff_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('idempotence_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=20), nullable=False),
    sa.Column('fulfillment_attempts', sa.Integer(), nullable=False),
    sa.Column('fulfillment_next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_error', sa.Text(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_notification_status', sa.String(length=20), nullable=False),
    sa.Column('owner_notification_attempts', sa.Integer(), nullable=False),
    sa.Column('owner_notification_next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_notification_error', sa.Text(), nullable=True),
    sa.Column('owner_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_payments_bot_id'), 'client_payments', ['bot_id'], unique=False)
    op.create_index(op.f('ix_client_payments_fulfillment_next_retry_at'), 'client_payments', ['fulfillment_next_retry_at'], unique=False)
    op.create_index(op.f('ix_client_payments_fulfillment_status'), 'client_payments', ['fulfillment_status'], unique=False)
    op.create_index(op.f('ix_client_payments_idempotence_key'), 'client_payments', ['idempotence_key'], unique=True)
    op.create_index(op.f('ix_client_payments_invoice_batch_id'), 'client_payments', ['invoice_batch_id'], unique=False)
    op.create_index(op.f('ix_client_payments_lead_id'), 'client_payments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_client_payments_owner_notification_next_retry_at'), 'client_payments', ['owner_notification_next_retry_at'], unique=False)
    op.create_index(op.f('ix_client_payments_owner_notification_status'), 'client_payments', ['owner_notification_status'], unique=False)
    op.create_index(op.f('ix_client_payments_provider_order_number'), 'client_payments', ['provider_order_number'], unique=True)
    op.create_index(op.f('ix_client_payments_provider_payment_id'), 'client_payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_client_payments_status'), 'client_payments', ['status'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('step_to_send', sa.String(length=255), nullable=False),
    sa.Column('raw_node_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execute_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_execute_at'), 'scheduled_tasks', ['execute_at'], unique=False)
    op.create_table('chat_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('client_payment_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=False),
    sa.Column('access_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_payment_id'], ['client_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_link')
    )
    op.create_index(op.f('ix_chat_access_grants_bot_id'), 'chat_access_grants', ['bot_id'], unique=False)
    op.create_index(op.f('ix_chat_access_grants_chat_id'), 'chat_access_grants', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_access_grants_client_payment_id'), 'chat_access_grants', ['client_payment_id'], unique=False)
    op.create_index(op.f('ix_chat_access_grants_lead_id'), 'chat_access_grants', ['lead_id'], unique=False)
    op.create_index(op.f('ix_chat_access_grants_status'), 'chat_access_grants', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.schema.DropSequence(sa.Sequence('client_payment_order_number_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_access_grants_status'), table_name='chat_access_grants')
    op.drop_index(op.f('ix_chat_access_grants_lead_id'), table_name='chat_access_grants')
    op.drop_index(op.f('ix_chat_access_grants_client_payment_id'), table_name='chat_access_grants')
    op.drop_index(op.f('ix_chat_access_grants_chat_id'), table_name='chat_access_grants')
    op.drop_index(op.f('ix_chat_access_grants_bot_id'), table_name='chat_access_grants')
    op.drop_table('chat_access_grants')
    op.drop_index(op.f('ix_scheduled_tasks_execute_at'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_client_payments_status'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_provider_payment_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_provider_order_number'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_owner_notification_status'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_owner_notification_next_retry_at'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_lead_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_invoice_batch_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_idempotence_key'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_fulfillment_status'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_fulfillment_next_retry_at'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_bot_id'), table_name='client_payments')
    op.drop_table('client_payments')
    op.drop_index(op.f('ix_media_assets_bot_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_leads_telegram_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_has_purchased'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_connected_chats_bot_id'), table_name='connected_chats')
    op.drop_table('connected_chats')
    op.drop_index(op.f('ix_saas_payments_yookassa_payment_id'), table_name='saas_payments')
    op.drop_index(op.f('ix_saas_payments_idempotence_key'), table_name='saas_payments')
    op.drop_table('saas_payments')
    op.drop_index(op.f('ix_bots_tg_bot_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
