"""remove_unique_client_payment_id

Revision ID: 5bd5d57cc7e5
Revises: g5b1d8e3f742
Create Date: 2026-08-05 16:30:04.579323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd5d57cc7e5'
down_revision: Union[str, Sequence[str], None] = 'g5b1d8e3f742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_access_grants_client_payment_id_key'), 'chat_access_grants', type_='unique')
    op.create_index(op.f('ix_chat_access_grants_chat_id'), 'chat_access_grants', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_access_grants_client_payment_id'), 'chat_access_grants', ['client_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_access_grants_client_payment_id'), table_name='chat_access_grants')
    op.drop_index(op.f('ix_chat_access_grants_chat_id'), table_name='chat_access_grants')
    op.create_unique_constraint(op.f('chat_access_grants_client_payment_id_key'), 'chat_access_grants', ['client_payment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
